# Generated by Django 4.0.4 on 2022-06-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "primary",
                    models.CharField(max_length=7, verbose_name="primary color"),
                ),
                (
                    "secondary",
                    models.CharField(max_length=7, verbose_name="secondary color"),
                ),
                ("accent", models.CharField(max_length=7, verbose_name="accent color")),
                (
                    "primary_fg",
                    models.CharField(
                        max_length=7, verbose_name="primary foreground color"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testapp.theme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
