# Generated by Django 4.0.3 on 2022-06-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="theme_name")),
                (
                    "primary",
                    models.CharField(max_length=60, verbose_name="primary color"),
                ),
                (
                    "secondary",
                    models.CharField(max_length=60, verbose_name="secondary color"),
                ),
                (
                    "accent",
                    models.CharField(max_length=60, verbose_name="accent color"),
                ),
                (
                    "primary_fg",
                    models.CharField(max_length=60, verbose_name="primary_fg"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="testapp.theme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
