# Generated by Django 4.0.3 on 2022-06-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="accent",
            field=models.CharField(max_length=60, verbose_name="accent"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=120, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary",
            field=models.CharField(max_length=60, verbose_name="primary"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="secondary",
            field=models.CharField(max_length=60, verbose_name="secondary"),
        ),
    ]
