name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
        django: ['2.2', '3.2']

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install tox tox-gh-actions codecov

      - name: Run tests
        run: |
          tox
          export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}
          codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DJANGO: ${{ matrix.django }}
